# Support Vector Regression

In [11]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm
from tqdm import tqdm
from sklearn.discriminant_analysis import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.svm import SVR

In [13]:
from sklearn.metrics import roc_curve, roc_auc_score, RocCurveDisplay , accuracy_score,mean_absolute_error

In [4]:
boston=pd.read_csv("D:\Machine Learning\Datasets\Boston.csv")
boston.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [7]:
X,y=boston.drop('medv',axis=1),boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)
print(f"Training samples: {X_train.shape[0]}, Test samples: {X_test.shape[0]}")

Training samples: 354, Test samples: 152

In [14]:

from sklearn.svm import SVR


std_scaler=StandardScaler()

cs=np.linspace(.001,5,15)
es=np.linspace(.001,5,15)
scores=[]
for e in tqdm(es):
    for c in cs:
        svm=SVR(kernel="linear",C=c,epsilon=e)
        pipe=Pipeline([("SCL",std_scaler),("SVC",svm)])
        pipe.fit(X_train,y_train)
        y_pred=pipe.predict(X_test)
        scores.append([c,e,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=('c','eps','score'))
df_scores.sort_values('score',ascending=False).head()

100%|██████████| 15/15 [00:02<00:00,  6.04it/s]

         c       eps     score
210  0.001  5.000000  5.604560
195  0.001  4.642929  5.582663
165  0.001  3.928786  5.579361
150  0.001  3.571714  5.579062
180  0.001  4.285857  5.573411

In [19]:

from sklearn.svm import SVR


std_scaler=StandardScaler()
gs=np.linspace(.001,5,15)
cs=np.linspace(.001,5,15)
es=np.linspace(.001,5,15)
scores=[]

for e in tqdm(es):
    for c in cs:
        for g in gs:
            svm=SVR(kernel="rbf",C=c,epsilon=e,gamma=g)
            pipe=Pipeline([("SCL",std_scaler),("SVC",svm)])
            pipe.fit(X_train,y_train)
            y_pred=pipe.predict(X_test)
            scores.append([c,e,g,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=('c','eps','gamma','score'))
df_scores.sort_values('score').head()

100%|██████████| 15/15 [00:38<00:00,  2.59s/it]

            c       eps     gamma     score
886  5.000000  1.072214  0.358071  2.780231
661  5.000000  0.715143  0.358071  2.786541
436  5.000000  0.358071  0.358071  2.788762
211  5.000000  0.001000  0.358071  2.814301
871  4.642929  1.072214  0.358071  2.818532

In [20]:
from sklearn.svm import SVR


std_scaler=StandardScaler()
gs=np.linspace(.001,5,15)
cs=np.linspace(.001,5,15)
es=np.linspace(.001,5,15)
scores=[]

for e in tqdm(es):
    for c in cs:
        for g in gs:
            svm=SVR(kernel="linear",C=c,epsilon=e,gamma=g)
            pipe=Pipeline([("SCL",std_scaler),("SVC",svm)])
            pipe.fit(X_train,y_train)
            y_pred=pipe.predict(X_test)
            scores.append([c,e,g,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=('c','eps','gamma','score'))
df_scores.sort_values('score').head()

100%|██████████| 15/15 [00:35<00:00,  2.37s/it]

            c       eps     gamma     score
262  0.715143  0.358071  2.500500  2.854736
263  0.715143  0.358071  2.857571  2.854736
264  0.715143  0.358071  3.214643  2.854736
265  0.715143  0.358071  3.571714  2.854736
267  0.715143  0.358071  4.285857  2.854736

In [ ]:
from sklearn.svm import SVR


std_scaler=StandardScaler()
gs=np.linspace(.001,5,15)
cs=np.linspace(.001,5,15)
es=np.linspace(.001,5,15)
scores=[]

for e in tqdm(es):
    for c in cs:
        for g in gs:
            svm=SVR(kernel="poly",C=c,epsilon=e,gamma=g)
            pipe=Pipeline([("SCL",std_scaler),("SVC",svm)])
            pipe.fit(X_train,y_train)
            y_pred=pipe.predict(X_test)
            scores.append([c,e,g,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=('c','eps','gamma','score'))
df_scores.sort_values('score').head()

  0%|          | 0/15 [00:00<?, ?it/s]

In [ ]:
from sklearn.svm import SVR


std_scaler=StandardScaler()
gs=np.linspace(.001,5,15)
cs=np.linspace(.001,5,15)
es=np.linspace(.001,5,15)
kernal=['linear','rbf','poly']
scores=[]
for k in tqdm(kernal):
    for e in es:
        for c in cs:
            for g in gs:
                svm=SVR(kernel=k,C=c,epsilon=e,gamma=g)
                pipe=Pipeline([("SCL",std_scaler),("SVC",svm)])
                pipe.fit(X_train,y_train)
                y_pred=pipe.predict(X_test)
                scores.append([c,e,g,kernal,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=('c','eps','gamma','kernal','score'))
df_scores.sort_values('score').head()