# Vehicles Dataset

In [3]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder

from sklearn.metrics import roc_curve, roc_auc_score, RocCurveDisplay , accuracy_score
import matplotlib.pyplot as plt

In [4]:
vehicle=pd.read_csv("D:\Machine Learning\Datasets\Cases\Vehicle_Silhouettes\Vehicle.csv")
vehicle

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,93,39,87,183,64,8,169,40,20,134,200,422,149,72,7,25,188,195,saab
842,89,46,84,163,66,11,159,43,20,159,173,368,176,72,1,20,186,197,van
843,106,54,101,222,67,12,222,30,25,173,228,721,200,70,3,4,187,201,saab
844,86,36,78,146,58,7,135,50,18,124,155,270,148,66,0,25,190,195,saab
845,85,36,66,123,55,5,120,56,17,128,140,212,131,73,1,18,186,190,van

In [5]:
le = LabelEncoder()
vehicle['Class'] = le.fit_transform(vehicle['Class'])
X,y=vehicle.drop('Class',axis=1),vehicle['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25,stratify=y)
print(f"Training samples: {X_train.shape[0]}, Test samples: {X_test.shape[0]}")
vehicle

Training samples: 592, Test samples: 254

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,3
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,3
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,2
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,3
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,93,39,87,183,64,8,169,40,20,134,200,422,149,72,7,25,188,195,2
842,89,46,84,163,66,11,159,43,20,159,173,368,176,72,1,20,186,197,3
843,106,54,101,222,67,12,222,30,25,173,228,721,200,70,3,4,187,201,2
844,86,36,78,146,58,7,135,50,18,124,155,270,148,66,0,25,190,195,2
845,85,36,66,123,55,5,120,56,17,128,140,212,131,73,1,18,186,190,3

In [6]:
std_scaler=StandardScaler()

Linear

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC


cs=np.linspace(.001,5,15)
dfs=['ovo','ovr']#ovo=one v one and ovr = one verses remaining
scores=[]
for s in tqdm(dfs):
    for c in cs:
        svm=SVC(kernel="linear",C=c,decision_function_shape=s)
        pipe=Pipeline([("SCL",std_scaler),("SVC",svm)])
        pipe.fit(X_train,y_train)
        y_pred=pipe.predict(X_test)
        scores.append([c,s,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=('c','decision','score'))
df_scores.sort_values('score',ascending=False).head()

100%|██████████| 2/2 [00:00<00:00,  3.53it/s]

           c decision     score
12  4.285857      ovo  0.842520
27  4.285857      ovr  0.842520
13  4.642929      ovo  0.838583
11  3.928786      ovo  0.838583
8   2.857571      ovo  0.838583

Polynomial

In [8]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC


cs=np.linspace(.001,5,15)
dfs=['ovo','ovr']#ovo=one v one and ovr = one verses remaining
scores=[]
for s in tqdm(dfs):
    for c in cs:
        svm=SVC(kernel="poly",C=c,decision_function_shape=s)
        pipe=Pipeline([("SCL",std_scaler),("SVC",svm)])
        pipe.fit(X_train,y_train)
        y_pred=pipe.predict(X_test)
        scores.append([c,s,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=('c','decision','score'))
df_scores.sort_values('score',ascending=False).head()

100%|██████████| 2/2 [00:00<00:00,  3.82it/s]

           c decision     score
29  5.000000      ovr  0.791339
14  5.000000      ovo  0.791339
13  4.642929      ovo  0.783465
28  4.642929      ovr  0.783465
27  4.285857      ovr  0.767717

RVf

In [9]:
cs=np.linspace(.001,5,15)
dfs=['ovo','ovr']#ovo=one v one and ovr = one verses remaining
scores=[]
for s in tqdm(dfs):
    for c in cs:
        svm=SVC(kernel="rbf",C=c,decision_function_shape=s)
        pipe=Pipeline([("SCL",std_scaler),("SVC",svm)])
        pipe.fit(X_train,y_train)
        y_pred=pipe.predict(X_test)
        scores.append([c,s,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=('c','decision','score'))
df_scores.sort_values('score',ascending=False).head()

100%|██████████| 2/2 [00:00<00:00,  3.01it/s]

           c decision     score
13  4.642929      ovo  0.795276
14  5.000000      ovo  0.795276
28  4.642929      ovr  0.795276
29  5.000000      ovr  0.795276
27  4.285857      ovr  0.791339

# Glass Identification

In [10]:
glass=pd.read_csv("D:\Machine Learning\Datasets\Cases\Glass_Identification\Glass.csv")

In [11]:
le = LabelEncoder()
glass['Type'] = le.fit_transform(glass['Type'])
X,y=glass.drop('Type',axis=1),glass['Type']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25,stratify=y)
print(f"Training samples: {X_train.shape[0]}, Test samples: {X_test.shape[0]}")

Training samples: 149, Test samples: 65

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC


cs=np.linspace(.001,5,15)
dfs=['ovo','ovr']#ovo=one v one and ovr = one verses remaining
kernal=['linear','poly','rbf']#kernals
scores=[]
for s in tqdm(dfs):
    for c in cs:
        for k in kernal:
            svm=SVC(kernel=k,C=c,decision_function_shape=s)
            pipe=Pipeline([("SCL",std_scaler),("SVC",svm)])
            pipe.fit(X_train,y_train)
            y_pred=pipe.predict(X_test)
            scores.append([c,s,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=('c','decision','score'))
df_scores.sort_values('score',ascending=False)

100%|██████████| 2/2 [00:00<00:00,  4.03it/s]

           c decision     score
41  4.642929      ovo  0.692308
38  4.285857      ovo  0.692308
89  5.000000      ovr  0.692308
44  5.000000      ovo  0.692308
86  4.642929      ovr  0.692308
..       ...      ...       ...
46  0.001000      ovr  0.369231
0   0.001000      ovo  0.353846
2   0.001000      ovo  0.353846
45  0.001000      ovr  0.353846
47  0.001000      ovr  0.353846

[90 rows x 3 columns]

In [13]:
# Get best for each decision function
best_per_decision = df_scores.loc[df_scores.groupby('decision')['score'].idxmax()]
best_per_decision

           c decision     score
38  4.285857      ovo  0.692308
83  4.285857      ovr  0.692308

---------------------------------------------------------------------

# Boston Dataset

In [ ]:
boston=pd.read_csv("D:\Machine Learning\Datasets\Boston.csv")

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9